### ISSUE TITLE
http://localhost:8080/manager_api/registApp?appName=%E5%95%8A%E6%96%AF%E8%92%82%E8%8A%AC

### ISSUE THREAD

**Issue by guozhenggang** [itboyspg/spg-code#1]
http://localhost:8080/manager_api/registApp?appName=%E5%95%8A%E6%96%AF%E8%92%82%E8%8A%AC

但是我的请求url是http://localhost:8080/{project-name}/manager_api/registApp?appName=%E5%95%8A%E6%96%AF%E8%92%82%E8%8A%AC

在哪里可以进行配置

**Comment by itboyspg** [comment]
manager_api不是项目名吗？你前面还加{project-name}干嘛？
